### ISSUE TITLE
Building/installation without docker?

### ISSUE THREAD

**Issue by kangasbros** [cloudtools/ssh-cert-authority#16]
Hi, currently when I try to execute build.sh, I get the following error: 

~/go/src/ssh-cert-authority$ bash build.sh 
# golang.org/x/crypto/ssh
../golang.org/x/crypto/ssh/keys.go:492: undefined: crypto.Signer

Is there some way to build and run this software without using docker? I'm unfamiliar with both docker and go, so quite newbie here...

**Comment by bobveznat** [comment]
Yes, building without docker works. I think you need to run `go get` first and then you can `go build` and `go run` `go test ./...`.=, `go install`.

Alternatively you can just download a pre-built binary from the Releases page here: https://github.com/cloudtools/ssh-cert-authority/releases/tag/1.2.0

Just download the right gzip (linux vs. os x), chmod +x it, and then run it. That's probably the shortest path to go time for you.
