### ISSUE TITLE
Use of deprecated function in urfave/cli

### ISSUE THREAD

**Issue by james-masson** [cloudtools/ssh-cert-authority#20]
I get this warning on most commands.

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

Everything still seems to work for now.

**Comment by bobveznat** [comment]
Thanks for letting me know about this, I've been happily running a build that was compiled a while ago and didn't have this warning. The fix is pushed and builds are building, I'll push a new release shortly.
