### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by ssephi** [cloudtools/ssh-cert-authority#25]
We internally use Alpine for our docker containers. 

Regardless of this, I am unable to build using the provided ubuntu buildenv or my standard alpine environment.

All builds regardless of build platform result in the same error:
./sign_certd.go:366: certChecker.IsAuthority undefined (type ssh.CertChecker has no field or method IsAuthority)

Using go versions: 1.7.3 on ubuntu, 1.7.5/1.8.1 on OSX and 1.7.3 on Alpine

Any assistance would be appreciated.

I will get one of my internal Go developers to take a look.

**Comment by bobveznat** [comment]
This appears to have broken a few days ago due to: https://github.com/golang/crypto/commit/527d12e53572562de9fd348d50e1ee4096803cec

Nice of them to clarify it was a "breaking change." I'm working on a patch now.

**Comment by bobveznat** [comment]
Fix pushed.
