### ISSUE TITLE
Requester can sign their own cert (when also listed as a signer)

### ISSUE THREAD

**Issue by Arvanaghi** [cloudtools/ssh-cert-authority#41]
It looks like an `AuthorizedRequester` can sign their own cert if they are also an `AuthorizedSigner` for the same environment. It seems intuitive for me that some requesters would also be signers for the same environment, and that requesters should not be able to sign a request for their own pubkey by default.

**Comment by bobveznat** [comment]
You've described the current behavior correctly. Is your expectation just that as a default a key cannot be used to sign a request if the signing key is == requesting key? And make an exception for if the config only has 1 key in it?

The last time I ran this in production I actually worked around this via lots of keys. I get this isn't appropriate for everyone. But I, as an individual, had signing keys for prod, staging and dev and user/requester keys for prod, staging and dev. This seems unintuitive and kind of lame actually, however, once you realize that ssh-agent can only store one certificate per public key you may end up wanting lots of keys.

Anyway, I'm interested in hearing what behavior you'd like to see.

**Comment by Arvanaghi** [comment]
Thanks for the quick reply!

I’d like to see disallowing the same key fingerprint being allowed to request and sign. For example, if you’re using some form of hardware token for your SSHing, you don’t have the luxury of multiple keys per environment.

**Comment by Arvanaghi** [comment]
Do you anticipate making a fix for this?
Wondering if I should try and block off some time.

**Comment by Arvanaghi** [comment]
Here you go! https://github.com/cloudtools/ssh-cert-authority/pull/42

**Comment by bobveznat** [comment]
Fixed with pr #42 . I updated the README and pushed the version to 2.0.0 since this may break backwards compatibility for folks. Thank you!
