### ISSUE TITLE
Documentation update: macOS *does* support ECDSA keys now

### ISSUE THREAD

**Issue by rhymeswithmogul** [cloudtools/ssh-cert-authority#44]
On your home page (README.md), you have the following quote:

> ECDSA support is nonexistent on OS X hosts unless your users build openssh from scratch (or homebrew). This is considered painful. This may not be a problem on more modern versions of OS X (i.e. high sierra) but I haven't tried it.

I can confirm that macOS Mojave comes with `OpenSSH_7.9p1, LibreSSL 2.7.3`, which supports all four key types (RSA, DSA, ECDSA, and Ed25519).  You may want to update your documentation.

**Comment by bobveznat** [comment]
Good catch, thank you for pointing this out. Addressed in commit b97bfb69.
